plugins { id 'com.android.application' }
android {
    namespace 'com.capture.clipper'
    compileSdk 34
    defaultConfig {
        applicationId "com.capture.clipper"
        minSdk 23
        targetSdk 34
        versionCode 8
        versionName "8.0"
    }
    lint { checkReleaseBuilds false; abortOnError false }
}
repositories { google(); mavenCentral(); maven { url 'https://jitpack.io' } }
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'com.github.jiangdongguo.AndroidUSBCamera:libuvccamera:v3.1.0'
}
