apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 34
    namespace "dev.alejandrorosas.streamlib"

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 34
    }
}

dependencies {
    implementation project(":libraries:libuvccamera")
    api "com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:2.2.4"
    implementation rootProject.ext.core
}
